// Full 42-peptide catalog ported from Helix spec v2.0 §12.
// Source monographs are summaries of published research literature.
// Dosing ranges are "research range only — not a recommendation."

export type Citation = { title: string; url: string };

export type Peptide = {
  id: string;
  name: string;
  subtitle: string;
  class: string; // e.g. 'HEALING / REGENERATIVE'
  color: string;
  sequence: string;
  formula: string;
  mw: string;
  halfLife: string;
  route: string;
  dose: string;
  freq: string;
  reconstitution: string;
  summary: string;
  mechanism: string; // markdown — paragraphs separated by \n\n
  stacks: string[];
  notes: string;
  citations: Citation[];
  // Explicit per-peptide default in micrograms. Authoritative; consumed by
  // log-dose / cycle-new / cycle-edit so the parser never has to guess from
  // dose strings like "0.25–2.4 mg weekly". Required.
  defaultDoseMcg: number;
  // v1.2.3: vial-strength presets shown as chips at the top of the
  // Reconstitute screen. Falls back to a universal [2, 5, 10, 15] mg if
  // unset. Override only when those four are misleading for this peptide
  // (e.g. GHK-Cu typically ships as 50 mg vials, NAD+ as 500 mg).
  commonVialSizes?: number[];
};

export const PEPTIDES: Peptide[] = [
  {
    id: 'bpc157',
    name: 'BPC-157',
    subtitle: 'Body Protection Compound 157',
    class: 'HEALING / REGENERATIVE',
    color: '#0A8E83',
    sequence: 'GEPPPGKPADDAGLV (pentadecapeptide, 15 aa)',
    formula: 'C62H98N16O22',
    mw: '1419.53 g/mol',
    halfLife: '~15–30 min',
    route: 'SubQ (most common) · IM · Oral (variable bioavailability)',
    dose: '200–500 mcg/day total, typically split into 1–2 SubQ doses',
    defaultDoseMcg: 250,
    freq: '1–2× daily during active cycle',
    reconstitution: '5 mg + 2 mL BAC = 2.5 mg/mL · 10 units = 250 mcg',
    summary: 'A synthetic 15-amino-acid sequence derived from a protein isolated from human gastric juice. Pre-clinical literature describes angiogenic, cyto-protective, and tissue-regenerative effects across a broad range of injury models. Human clinical data remains limited — most evidence is from rodent and in-vitro studies.',
    mechanism: 'Angiogenesis (ERK1/2 pathway). Phosphorylates ERK1/2 in endothelial cells in a dose-dependent manner, driving proliferation, migration, and vascular tube formation. Downstream c-Fos, c-Jun, and EGR-1 transcription factors regulate extracellular matrix remodeling.\n\nGrowth hormone receptor upregulation. Increases GH-receptor expression in tendon fibroblasts — a proposed mechanism for the peptide\'s reported tendon/ligament healing effects.\n\nNitric oxide / vascular tone. Modulates the NO system; preclinical work describes rapid collateral vessel activation that bypasses occluded pathways in vessel-occlusion models.\n\nAnti-inflammatory cytokine modulation. Reduces pro-inflammatory cytokine expression while preserving healing-phase inflammation needed for repair.',
    stacks: ['TB-500', 'GHK-Cu', 'KPV'],
    notes: 'Half-life (<30 min) is short — twice-daily dosing is common in research protocols. Temporarily banned by WADA in 2022; currently not on the prohibited list but status can change. Not FDA-approved.',
    citations: [
      { title: 'Multifunctionality and Possible Medical Application of the BPC 157 Peptide—Literature Review. Pharmaceuticals (MDPI), 2025.', url: 'https://www.mdpi.com/1424-8247/18/2/185' },
      { title: 'Pharmacokinetics, distribution, metabolism, and excretion of BPC157 in rats and dogs. Frontiers in Pharmacology, 2022.', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9794587/' },
      { title: 'Regeneration or Risk? A Narrative Review of BPC-157 for Musculoskeletal Healing. PMC, 2025.', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12446177/' },
    ],
  },
  {
    id: 'tb500',
    name: 'TB-500',
    subtitle: 'Thymosin β4 fragment',
    class: 'HEALING / REGENERATIVE',
    color: '#C48A2E',
    sequence: 'Ac-LKKTETQ (7 aa; N-terminally acetylated)',
    formula: 'C38H68N10O14',
    mw: '889.02 g/mol',
    halfLife: '~6–8 h (plasma); tissue effects persist longer',
    route: 'SubQ or IM',
    dose: '2–5 mg per dose (research protocols)',
    defaultDoseMcg: 2500,
    freq: '1–2× per week loading; then weekly maintenance',
    reconstitution: '10 mg + 5 mL BAC = 2.0 mg/mL · 25 units = 0.5 mg',
    summary: 'A synthetic 7-amino-acid fragment corresponding to the actin-binding motif of the endogenous 43-amino-acid protein thymosin β4. Used in research on cytoskeletal remodeling, cell migration, and tissue repair. Often colloquially conflated with full-length TB4; they are biochemically distinct.',
    mechanism: '\n\nG-actin sequestration. Binds monomeric G-actin, influencing polymerization dynamics and the cytoskeletal remodeling required for cell migration to injury sites.\n\nMMP-2 upregulation. Studies report 3–4× upregulation of matrix metalloproteinase-2, which remodels extracellular matrix during repair.\n\nAngiogenesis. Promotes endothelial cell proliferation and capillary density; animal models show ~40% increased capillary density in treated wound sites.\n\nAnti-inflammatory. Reduces pro-inflammatory cytokine signaling and supports resolution-phase macrophage activity.',
    stacks: ['BPC-157', 'GHK-Cu'],
    notes: 'Note that TB-500 is only a fragment of the endogenous Tβ4 peptide; full-length Tβ4 has additional domain-dependent effects not reproduced by the 7-aa fragment. Prohibited by WADA.',
    citations: [
      { title: 'Thymosin β4: a multi-functional regenerative peptide — Goldstein AL et al.. Expert Opin Biol Ther, 2012.', url: 'https://pubmed.ncbi.nlm.nih.gov/22171664/' },
      { title: 'Investigation of in vitro/ex vivo TB-500 metabolism. WADA / World Anti-Doping Agency, 2023. esis-relevant', url: 'https://www.wada-ama.org/en/resources/scientific-research/investigation-vitroex-vivo-tb-500-metabolism-synth' },
      { title: 'Utilizing Developmentally Essential Secreted Peptides Such as Thymosin Beta-4. International Journal of Molecular Sciences, 2021.', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8228050/' },
    ],
  },
  {
    id: 'tb4_full',
    name: 'Thymosin β4 (full length)',
    subtitle: 'Endogenous 43-aa actin-binding protein',
    class: 'HEALING / REGENERATIVE',
    color: '#C48A2E',
    sequence: '43 aa (full sequence encoded by TMSB4X gene)',
    formula: 'C212H350N56O78S',
    mw: '~4,963 g/mol',
    halfLife: 'Short in plasma (minutes); domain effects extend via tissue binding',
    route: 'SubQ or IM',
    dose: 'Research protocols vary, typically 2–10 mg range',
    defaultDoseMcg: 5000,
    freq: '2–3× weekly in most research protocols',
    reconstitution: 'Depends on vial strength; consult reconstitution calculator',
    summary: 'The full-length endogenous protein from which TB-500 is derived. Unlike TB-500, Tβ4 retains multiple functional domains beyond the actin-binding motif, including regions implicated in corneal healing, cardiac repair, and neurological protection in preclinical models.',
    mechanism: 'Actin filament assembly regulation. Influences both polymerization and depolymerization dynamics via G-actin binding.\n\nEmbryonic re-activation. Preclinical studies show systemic Tβ4 can reactivate dormant epicardial progenitor cells in adult mammalian heart.\n\nCorneal / ocular surface healing. Investigated in phase II/III trials for neurotrophic keratopathy and dry eye.',
    stacks: ['BPC-157', 'GHK-Cu'],
    notes: 'Research-only. Human clinical trials have been conducted (cornea, dry eye, venous stasis ulcers) but no FDA-approved formulation exists as of 2026.',
    citations: [
      { title: 'Goldstein AL et al. — Thymosin β4 properties and clinical applications. Expert Opin Biol Ther, 2012.', url: 'https://pubmed.ncbi.nlm.nih.gov/22171664/' },
      { title: 'Thymosin Beta 4: Potential Novel Therapy for Neurotrophic Keratopathy. Sosne G et al., 2016.', url: 'https://pubmed.ncbi.nlm.nih.gov/26900032/' },
    ],
  },
  {
    id: 'ghkcu',
    name: 'GHK-Cu',
    subtitle: 'Copper tripeptide (Gly-His-Lys)',
    class: 'HEALING / SKIN',
    color: '#1A8A4F',
    sequence: 'Gly-His-Lys (3 aa) complexed with Cu²■',
    formula: 'C14H24N6O4Cu',
    mw: '~340 g/mol',
    halfLife: 'Minutes (plasma); sustained tissue effects via copper chelation',
    route: 'SubQ · Topical · (very rarely)',
    dose: '1–3 mg SubQ; topical formulations 0.05–2% w/w',
    defaultDoseMcg: 2000,
  commonVialSizes: [10, 50, 100, 200],
    freq: 'Daily SubQ or topical 1–2× daily',
    reconstitution: '50 mg + 5 mL BAC = 10 mg/mL · 10 units = 1 mg',
    summary: 'A naturally occurring copper-binding tripeptide present in human plasma, saliva, and urine. Genomic studies suggest GHK-Cu modulates expression of over 4,000 human genes. Most extensively studied in dermatologic and wound-healing contexts.',
    mechanism: 'Collagen / elastin synthesis. Stimulates fibroblast production of collagen, elastin, and proteoglycans via upregulation of prolyl hydroxylase.\n\nAntioxidant defense. Enhances superoxide dismutase (SOD) activity 2–3×; copper cofactor delivery amplifies endogenous ROS scavenging.\n\nAngiogenesis and nerve outgrowth. Promotes blood vessel formation and peripheral nerve regeneration in wound-healing models.\n\nGene expression modulation. Affects >4,000 genes — broad influence on tissue repair, anti-inflammatory signaling, and cell-cycle regulation.',
    stacks: ['BPC-157', 'TB-500'],
    notes: 'Topical use is best-evidenced. SubQ injection can stain skin blue-green transiently due to copper. Do not co-administer with vitamin C at same site.',
    citations: [
      { title: 'Pickart L, Margolina A — GHK Peptide as a Natural Modulator in Skin Regeneration. Int J Mol Sci, 2018.', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4508379/' },
      { title: 'Regenerative and Protective Actions of the GHK-Cu Peptide. Oxid Med Cell Longev, 2015.', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6073405/' },
      { title: 'The Potential of GHK as an Anti-Aging Peptide. Aging & Disease, 2022.', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8789089/' },
    ],
  },
  {
    id: 'pda',
    name: 'Pentadeca Arginate (PDA)',
    subtitle: 'Arginate-salt analog of BPC-157',
    class: 'HEALING / REGENERATIVE',
    color: '#0A8E83',
    sequence: 'Same 15 aa sequence as BPC-157 with arginate counter-ion',
    formula: 'C62H98N16O22',
    mw: '~1,419 g/mol (base peptide)',
    halfLife: 'Reportedly longer than BPC-157; limited PK data',
    route: 'SubQ',
    dose: '250–500 mcg/day (same range as BPC-157)',
    defaultDoseMcg: 250,
  commonVialSizes: [5, 10, 25],
    freq: '1–2× daily',
    reconstitution: '10 mg + 2 mL BAC = 5 mg/mL · 5 units = 250 mcg',
    summary: 'An arginate salt form of the BPC-157 pentadecapeptide introduced in response to compounding restrictions on BPC-157. Proposed to offer improved stability and shelf life; human pharmacokinetic data remains sparse.',
    mechanism: 'See BPC-157. Mechanistic profile is believed to overlap substantially with BPC-157 given the identical peptide sequence. Differences, if any, arise from the counter-ion\'s effect on stability and bioavailability.',
    stacks: ['TB-500', 'GHK-Cu'],
    notes: 'Emerging in 2024–2025 as a BPC-157 alternative in the compounding market. Independent head-to-head pharmacokinetic comparisons are not yet published.',
    citations: [
      { title: 'Emerging use of Pentadeca Arginate — industry technical briefs. Compounding pharmacy whitepapers, 2024. Industry references', url: '' },
    ],
  },
  {
    id: 'kpv',
    name: 'KPV',
    subtitle: 'α-MSH C-terminal tripeptide',
    class: 'IMMUNE / ANTI-INFLAMMATORY',
    color: '#4F86C9',
    sequence: 'Lys-Pro-Val (3 aa)',
    formula: 'C16H30N4O4',
    mw: '342.44 g/mol',
    halfLife: '~1–2 h',
    route: 'SubQ · Oral (investigated) · Topical',
    dose: '200–500 mcg/day (research)',
    defaultDoseMcg: 250,
    freq: '1× daily',
    reconstitution: '5 mg + 2 mL BAC = 2.5 mg/mL · 10 units = 250 mcg',
    summary: 'A C-terminal tripeptide of alpha-melanocyte stimulating hormone (α-MSH). Retains α-MSH\'s anti-inflammatory effects without pigmentation activity. Studied for IBD, psoriasis, wound infection, and gut mucosal healing.',
    mechanism: 'NF-κB inhibition. Suppresses pro-inflammatory NF-κB signaling in intestinal epithelial cells and macrophages.\n\nAntimicrobial activity. Direct activity against several pathogens including S. aureus and Candida albicans in vitro.\n\nMacrophage modulation. Reduces pro-inflammatory cytokine release while preserving host defense.',
    stacks: ['BPC-157', 'GHK-Cu'],
    notes: 'Often paired with BPC-157 for GI-focused protocols.',
    citations: [
      { title: 'Dalmasso G et al. — KPV, a tripeptide from α-MSH, attenuates colitis. Gut, 2008.', url: '' },
    ],
  },
  {
    id: 'ta1',
    name: 'Thymosin Alpha-1',
    subtitle: 'Immunomodulatory 28-aa peptide',
    class: 'IMMUNE',
    color: '#4F86C9',
    sequence: 'Ac-Ser-Asp-Ala-Ala-Val-Asp-Thr-... (28 aa N-acetylated)',
    formula: 'C129H215N33O55',
    mw: '3,108.4 g/mol',
    halfLife: '~2 h',
    route: 'SubQ',
    dose: '1.6 mg SubQ 2× weekly (clinical label)',
    defaultDoseMcg: 1600,
    freq: '2× weekly',
    reconstitution: '5 mg + 1 mL BAC = 5 mg/mL · 32 units = 1.6 mg (clinical label dose)',
    summary: 'An N-acetylated 28-amino-acid peptide originally isolated from thymus gland. Approved in 35+ countries as Zadaxin for hepatitis B, hepatitis C, and as adjunct in cancer immunotherapy. Not FDA-approved in the US.',
    mechanism: 'TLR9 activation. Signals through Toll-like receptor 9 on plasmacytoid dendritic cells, stimulating type-I interferon response.\n\nT-cell maturation. Promotes CD4+/CD8+ T-cell differentiation and IL-2 receptor expression.\n\nNK cell activation. Increases natural-killer-cell cytotoxicity.',
    stacks: [],
    notes: 'Used in clinical protocols for chronic viral infection and cancer adjunct.',
    citations: [
      { title: 'Garaci E et al. — Thymosin alpha-1 in the treatment of cancer. Expert Opin Biol Ther, 2007.', url: 'https://pubmed.ncbi.nlm.nih.gov/17696815/' },
    ],
  },
  {
    id: 'll37',
    name: 'LL-37',
    subtitle: 'Human cathelicidin antimicrobial peptide',
    class: 'IMMUNE / ANTIMICROBIAL',
    color: '#4F86C9',
    sequence: '37 aa; cleaved from human cathelicidin (CAMP gene)',
    formula: 'C205H340N60O53',
    mw: '4,493.27 g/mol',
    halfLife: '~1 h',
    route: 'SubQ · Topical · Nebulized (research)',
    dose: '100–500 mcg SubQ (research); topical formulations vary',
    defaultDoseMcg: 250,
    freq: 'Daily in research protocols',
    reconstitution: '5 mg + 2 mL BAC = 2.5 mg/mL · 4 units = 100 mcg',
    summary: 'The only human cathelicidin. Endogenous antimicrobial peptide active against gram-positive and gram-negative bacteria, fungi, and some enveloped viruses. Under investigation for chronic biofilm infections and mycobacterial disease.',
    mechanism: 'Membrane disruption. Amphipathic α-helical structure inserts into bacterial cell membranes, creating pores.\n\nImmunomodulation. Acts on host immune cells through FPR2 and P2X7 receptors; chemotactic for neutrophils and T-cells.',
    stacks: [],
    notes: 'Primarily an antimicrobial research tool; not clinically approved.',
    citations: [
      { title: 'Dürr UH et al. — LL-37, the only human cathelicidin. Biochim Biophys Acta, 2006.', url: 'https://pubmed.ncbi.nlm.nih.gov/16842997/' },
    ],
  },
  {
    id: 'ipamor',
    name: 'Ipamorelin',
    subtitle: 'Selective GH secretagogue',
    class: 'GROWTH / GHRP',
    color: '#7A4FC9',
    sequence: 'Aib-His-D-2-Nal-D-Phe-Lys-NH■ (pentapeptide)',
    formula: 'C38H49N9O5',
    mw: '711.86 g/mol',
    halfLife: '~2 h',
    route: 'SubQ',
    dose: '200–300 mcg per injection (typical research range)',
    defaultDoseMcg: 250,
    freq: '1–3× daily (pulsatile dosing matches physiologic GH pulses)',
    reconstitution: '5 mg + 2 mL BAC = 2.5 mg/mL · 10 units = 250 mcg',
    summary: 'A selective growth hormone secretagogue that mimics ghrelin, binding the GHSR-1a receptor in the anterior pituitary to release endogenous GH in a pulsatile pattern resembling physiologic secretion. Unlike earlier GHRPs (GHRP-2/6), Ipamorelin is reported to have minimal effect on cortisol and prolactin, earning it a \'clean pulse\' reputation in the literature.',
    mechanism: 'GHSR-1a agonism. Binds growth-hormone secretagogue receptor type 1a in the pituitary, triggering GH release via Gq-coupled IP3/DAG signaling.\n\nGhrelin mimicry. Mimics the natural GH-releasing action of ghrelin without the appetite or cortisol-stimulating effects of other ghrelin analogs.\n\nSynergy with GHRH-class peptides. Combines with CJC-1295 or Sermorelin to produce amplified GH pulses — the two pathways (ghrelin-mimetic and GHRH-mimetic) converge synergistically on pituitary somatotrophs.',
    stacks: ['CJC-1295 (no DAC / Mod GRF 1-29)', 'CJC-1295 DAC', 'Sermorelin'],
    notes: 'Classic stack partner is CJC-1295 (no DAC) for combined GHRP + GHRH pulse. Best timed at bedtime (2+ h post-meal) to align with physiologic GH pulses.',
    citations: [
      { title: 'Raun K et al. — Ipamorelin, the first selective GH secretagogue. Eur J Endocrinol, 1998.', url: 'https://pubmed.ncbi.nlm.nih.gov/9849822/' },
      { title: 'Sinha DK et al. — GH secretagogues: clinical applications. Transl Androl Urol, 2020.', url: 'https://pubmed.ncbi.nlm.nih.gov/32257858/' },
    ],
  },
  {
    id: 'cjc_nodac',
    name: 'CJC-1295 (no DAC)',
    subtitle: 'Mod GRF 1-29 — GHRH analog',
    class: 'GROWTH / GHRH',
    color: '#7A4FC9',
    sequence: 'Modified GRF(1-29) with stability substitutions',
    formula: 'C152H252N44O42',
    mw: '3,367.9 g/mol',
    halfLife: '~30 min – 1 h',
    route: 'SubQ',
    dose: '100 mcg per injection (typical)',
    defaultDoseMcg: 100,
    freq: '1–3× daily, paired with a GHRP at each pulse',
    reconstitution: '2 mg + 2 mL BAC = 1 mg/mL · 10 units = 100 mcg',
    summary: 'A modified 29-amino-acid fragment of natural GHRH, engineered with amino-acid substitutions that resist DPP-4 degradation. Sustains a natural GH pulse shape. Distinct from CJC-1295 DAC, which is covalently linked to a lysine-maleimido-propionyl group that binds serum albumin.',
    mechanism: 'GHRH receptor agonism. Binds the GHRH receptor on pituitary somatotrophs, activating cAMP/PKA and provoking GH synthesis and release.\n\nPulse amplification. Does not override the pituitary\'s endogenous feedback — augments natural pulses rather than producing a sustained elevation.\n\nDPP-4 resistance. Aib substitution at position 2 prevents the rapid DPP-4 cleavage that limits native GHRH to a 2–7 min half-life.',
    stacks: ['Ipamorelin', 'GHRP-2', 'GHRP-6'],
    notes: 'Often stacked with Ipamorelin or another GHRP. \'Mod GRF 1-29\' is the same molecule — naming confusion is common.',
    citations: [
      { title: 'Jetté L et al. — hGRF analogs with drug affinity complex technology. J Pharmacol Exp Ther, 2005.', url: 'https://pubmed.ncbi.nlm.nih.gov/15831434/' },
      { title: 'Teichman SL et al. — CJC-1295 in healthy adults. J Clin Endocrinol Metab, 2006.', url: 'https://pubmed.ncbi.nlm.nih.gov/16352683/' },
    ],
  },
  {
    id: 'cjc_dac',
    name: 'CJC-1295 DAC',
    subtitle: 'GHRH analog with drug affinity complex',
    class: 'GROWTH / GHRH',
    color: '#7A4FC9',
    sequence: 'Modified GRF(1-29) + lysine-maleimidopropionate (MPA) linker',
    formula: 'C165H269N47O46',
    mw: '3,647.2 g/mol',
    halfLife: '~6–8 days (albumin-bound)',
    route: 'SubQ',
    dose: '1–2 mg per injection',
    defaultDoseMcg: 1000,
    freq: 'Once weekly (twice weekly in some protocols)',
    reconstitution: '2 mg + 1 mL BAC = 2 mg/mL · 50 units = 1 mg',
    summary: 'CJC-1295 with a covalent lysine-maleimido-propionyl (DAC) group that binds irreversibly to circulating serum albumin, extending plasma half-life to roughly a week. A single injection raises GH 2–10× for 6 days and IGF-1 0.5–3× for 9–11 days in humans. ',
    mechanism: 'Albumin piggybacking. The MPA linker forms a covalent bond with free cysteine residues on albumin, creating an extended-circulation prodrug.\n\nSustained GHRH signaling. Produces a GH \'bleed\' pattern rather than the sharp pulses of the no-DAC variant — higher baseline GH but muted peak amplitudes.\n\nIGF-1 elevation. Prolonged GH signaling drives sustained IGF-1 elevation — the primary readout in dosing studies.',
    stacks: ['Ipamorelin'],
    notes: 'DAC version is controversial in research circles: sustained elevation may not mimic physiologic pulsatile GH as closely as the no-DAC variant. FDA-warned for immunogenicity risk.',
    citations: [
      { title: 'Teichman SL et al. — Prolonged stimulation of GH and IGF-1 secretion by CJC-1295. J Clin Endocrinol Metab, 2006.', url: 'https://pubmed.ncbi.nlm.nih.gov/16352683/' },
      { title: 'Wikipedia — CJC-1295 pharmacokinetics summary. Wikipedia, 2025.', url: 'https://en.wikipedia.org/wiki/CJC-1295' },
    ],
  },
  {
    id: 'sermor',
    name: 'Sermorelin',
    subtitle: 'GRF(1-29) — native GHRH fragment',
    class: 'GROWTH / GHRH',
    color: '#7A4FC9',
    sequence: 'Native GHRH(1-29)',
    formula: 'C149H246N44O42S',
    mw: '3,357.9 g/mol',
    halfLife: '~10–20 min',
    route: 'SubQ',
    dose: '200–500 mcg per injection',
    defaultDoseMcg: 300,
    freq: 'Nightly (at bedtime to align with natural GH pulse)',
    reconstitution: '5 mg + 2 mL BAC = 2.5 mg/mL · 10 units = 250 mcg',
    summary: 'The first 29 amino acids of endogenous human GHRH. Formerly marketed as Geref for pediatric GH deficiency (withdrawn 2008 for commercial reasons). Short half-life limits GH pulse duration and may stimulate modest cortisol/prolactin.',
    mechanism: 'GHRH receptor agonism. Identical action to native GHRH at the pituitary GHRH receptor; cAMP-mediated GH release.\n\nRapid clearance. 10–20 minute half-life means the GH pulse is short — mimics physiology more closely than DAC variants but requires more frequent dosing.',
    stacks: ['Ipamorelin', 'GHRP-2'],
    notes: 'Still prescribed off-label through compounding pharmacies for adult GH deficiency. Historically used as diagnostic agent for GH reserve.',
    citations: [
      { title: 'Walker RF — Sermorelin: A better approach to management of adult-onset GH insufficiency. Clin Interv Aging, 2006.', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC2695167/' },
    ],
  },
  {
    id: 'tesamor',
    name: 'Tesamorelin',
    subtitle: 'Stabilized GHRH analog (Egrifta®)',
    class: 'GROWTH / GHRH',
    color: '#7A4FC9',
    sequence: 'N-terminal trans-3-hexenoyl-modified GHRH(1-44)',
    formula: 'C221H366N72O67S',
    mw: '5,135.8 g/mol',
    halfLife: '~30 min (SubQ)',
    route: 'SubQ',
    dose: '1–2 mg daily (FDA label: 2 mg SubQ once daily)',
    defaultDoseMcg: 2000,
  commonVialSizes: [5, 10, 20],
    freq: 'Once daily',
    reconstitution: '10 mg + 2 mL sterile water = 5 mg/mL · 20 units = 1 mg',
    summary: 'FDA-approved GHRH analog (Egrifta® / Egrifta SV) for reduction of excess abdominal fat in HIV-associated lipodystrophy. The only FDA-approved GH-secretagogue peptide currently in broad use. Strong clinical data for visceral adipose tissue reduction and secondary benefits on liver fat.',
    mechanism: 'GHRH receptor agonism. Stabilized analog of native GHRH that resists DPP-4 degradation; induces physiologic GH and IGF-1 increases.\n\nVisceral fat reduction. Clinical trials show 15–18% reduction in visceral adipose tissue over 6 months — attributed to GH-mediated lipolysis of visceral depots.\n\nHepatic fat improvement. Phase II/III trials in NAFLD show reductions in liver fat fraction and fibrosis markers.',
    stacks: ['Ipamorelin'],
    notes: 'Use sterile (non-bacteriostatic) water for reconstitution per FDA label. Contraindicated in active malignancy; monitor fasting glucose during use.',
    citations: [
      { title: 'Falutz J et al. — Tesamorelin, a GHRH analog, in HIV-associated lipodystrophy. NEJM, 2007.', url: 'https://pubmed.ncbi.nlm.nih.gov/17977293/' },
      { title: 'Stanley TL et al. — Tesamorelin reduces liver fat in NAFLD. Lancet HIV, 2019.', url: 'https://doi.org/10.1016/S2352-3018(19)30338-8' },
    ],
  },
  {
    id: 'hexar',
    name: 'Hexarelin',
    subtitle: 'Potent GHRP with strong GH release',
    class: 'GROWTH / GHRP',
    color: '#7A4FC9',
    sequence: 'His-D-2-MeTrp-Ala-Trp-D-Phe-Lys-NH■',
    formula: 'C47H58N12O6',
    mw: '887.04 g/mol',
    halfLife: '~55 min',
    route: 'SubQ',
    dose: '100–200 mcg per dose',
    defaultDoseMcg: 100,
    freq: '1–3× daily (tolerance builds quickly)',
    reconstitution: '5 mg + 2 mL BAC = 2.5 mg/mL · 4 units = 100 mcg',
    summary: 'The most potent of the classic GHRPs, producing stronger GH pulses than GHRP-6 or Ipamorelin but with meaningful cortisol and prolactin effects. Research-only. Rapid receptor desensitization is well documented — tolerance builds within weeks of daily use.',
    mechanism: 'GHSR-1a agonism. Strong ghrelin-receptor agonist; induces the largest GH pulses of any classic GHRP.\n\nCardiac-specific CD36 binding. Distinct from pure GHSR-1a effect: Hexarelin has cardioprotective effects in rodent ischemia models via CD36 binding, independent of GH release.',
    stacks: ['CJC-1295 (no DAC / Mod GRF 1-29)'],
    notes: 'Tolerance is real — GH response declines after ~2 weeks of daily dosing. Pulsed protocols (5-on/5-off) are common in research.',
    citations: [
      { title: 'Imbimbo BP et al. — Growth hormone-releasing activity of hexarelin in humans. Eur J Clin Pharmacol, 1994.', url: 'https://pubmed.ncbi.nlm.nih.gov/7957505/' },
    ],
  },
  {
    id: 'ghrp2',
    name: 'GHRP-2',
    subtitle: 'Growth Hormone Releasing Peptide-2',
    class: 'GROWTH / GHRP',
    color: '#7A4FC9',
    sequence: 'D-Ala-D-2-Nal-Ala-Trp-D-Phe-Lys-NH■',
    formula: 'C45H55N9O6',
    mw: '817.95 g/mol',
    halfLife: '~15–30 min',
    route: 'SubQ',
    dose: '100–300 mcg per dose',
    defaultDoseMcg: 200,
    freq: '1–3× daily',
    reconstitution: '5 mg + 2 mL BAC = 2.5 mg/mL · 10 units = 250 mcg',
    summary: 'A ghrelin-receptor agonist used in Japan as a diagnostic agent for GH deficiency (under the name Pralmorelin). Stimulates GH, but also mildly elevates cortisol, prolactin, and appetite.',
    mechanism: 'GHSR-1a agonism. Binds the ghrelin receptor, promoting GH release via the phospholipase-C pathway.\n\nAppetite stimulation. Mild ghrelin-like effects on appetite are clinically meaningful, distinguishing GHRP-2 from Ipamorelin.',
    stacks: ['CJC-1295 (no DAC / Mod GRF 1-29)'],
    notes: 'Approved in Japan for GH diagnostic testing; not FDA-approved in US.',
    citations: [
      { title: 'Bowers CY et al. — Growth hormone-releasing peptides. Cell Mol Life Sci, 1998.', url: 'https://pubmed.ncbi.nlm.nih.gov/9891344/' },
    ],
  },
  {
    id: 'ghrp6',
    name: 'GHRP-6',
    subtitle: 'Classic hexapeptide GH secretagogue',
    class: 'GROWTH / GHRP',
    color: '#7A4FC9',
    sequence: 'His-D-Trp-Ala-Trp-D-Phe-Lys-NH■',
    formula: 'C46H56N12O6',
    mw: '872.44 g/mol',
    halfLife: '~15–60 min',
    route: 'SubQ',
    dose: '100–300 mcg per dose',
    defaultDoseMcg: 200,
    freq: '2–3× daily',
    reconstitution: '5 mg + 2 mL BAC = 2.5 mg/mL · 10 units = 250 mcg',
    summary: 'The original ghrelin-mimetic hexapeptide. Produces strong GH release accompanied by pronounced appetite stimulation, which was historically used to investigate ghrelin biology.',
    mechanism: 'GHSR-1a agonism. Parent compound for the GHRP series; full ghrelin agonist.\n\nAppetite stimulation. Most pronounced ghrelin-mimetic effects of the class.',
    stacks: ['CJC-1295 (no DAC / Mod GRF 1-29)'],
    notes: 'Appetite effects make it unsuitable for weight-loss protocols.',
    citations: [
      { title: 'Bowers CY — History and perspective of growth hormone-releasing peptides. Endocrine, 2001.', url: 'https://pubmed.ncbi.nlm.nih.gov/11732755/' },
    ],
  },
  {
    id: 'mk677',
    name: 'MK-677 (Ibutamoren)',
    subtitle: 'Oral ghrelin-receptor agonist',
    class: 'GROWTH / SMALL MOLECULE',
    color: '#7A4FC9',
    sequence: 'Not a peptide — small-molecule GHSR-1a agonist',
    formula: 'C27H36N4O5S',
    mw: '528.66 g/mol',
    halfLife: '~6 h',
    route: 'Oral',
    dose: '10–25 mg orally, nightly',
    defaultDoseMcg: 10000,
    freq: 'Nightly',
    reconstitution: 'Capsules / solution; not reconstituted',
    summary: 'Not a peptide but commonly grouped with peptide GH secretagogues. A non-peptide, orally bioavailable ghrelin-receptor (GHSR-1a) agonist. Raises GH and IGF-1 with once-daily oral dosing. Development as a clinical drug was halted in part due to concerns about fluid retention and insulin resistance at long-term use.',
    mechanism: 'GHSR-1a agonism (oral). Same target as Ipamorelin and GHRP-6, but as a small molecule with oral bioavailability and 6-hour half-life — producing a single daily GH \'bleed\' rather than pulses.',
    stacks: ['CJC-1295 (no DAC / Mod GRF 1-29)', 'Ipamorelin'],
    notes: 'Appetite and water retention are common. Long-term use may worsen insulin sensitivity. Not recommended for diabetics.',
    citations: [
      { title: 'Nass R et al. — Effects of an oral ghrelin mimetic on body composition. Ann Intern Med, 2008.', url: 'https://pubmed.ncbi.nlm.nih.gov/18987334/' },
    ],
  },
  {
    id: 'sema',
    name: 'Semaglutide',
    subtitle: 'Long-acting GLP-1 agonist (Ozempic®)',
    class: 'METABOLIC / GLP-1',
    color: '#2A6BB5',
    sequence: 'GLP-1(7-37) with Aib at pos 8 and C18 fatty diacid at Lys26',
    formula: 'C187H291N45O59',
    mw: '4,113.58 g/mol',
    halfLife: '~7 days (≈160 h)',
    route: 'SubQ weekly (or oral daily as Rybelsus®)',
    dose: '0.25–2.4 mg weekly (titrated)',
    defaultDoseMcg: 250,
    freq: 'Once weekly (SubQ); Once daily fasting (oral)',
    reconstitution: 'Pre-filled pens (Ozempic / Wegovy / Rybelsus oral) are standard. Research powder: 5 mg + 2 mL BAC = 2.5 mg/mL · 10 units = 250 mcg starting dose. Titrate per clinical protocol (0.25 → 0.5 → 1 → 1.7 → 2.4 mg weekly).',
    summary: 'A long-acting GLP-1 receptor agonist engineered from native GLP-1 via α-aminoisobutyric acid substitution at position 8 (DPP-4 resistance) and C18 fatty diacid conjugation at Lys26 (albumin binding). FDA-approved for type 2 diabetes (Ozempic), obesity (Wegovy), and cardiovascular risk reduction in selected adults.',
    mechanism: 'GLP-1 receptor agonism. Full agonist of the GLP-1 receptor on pancreatic β-cells, delayed gastric emptying neurons, and central satiety centers in the hypothalamus and brainstem.\n\nGlucose-dependent insulinotropic. Stimulates insulin release only when blood glucose is elevated — near-zero risk of hypoglycemia in monotherapy.\n\nCentral appetite suppression. Acts on hindbrain and hypothalamic GLP-1R neurons to reduce food intake; STEP trials show average 14–17% weight loss over 68 weeks.\n\nAlbumin-bound pharmacokinetics. The C18 diacid binds serum albumin reversibly, shielding the peptide from renal filtration and proteolysis — enabling weekly dosing.',
    stacks: ['Tirzepatide', 'Retatrutide', 'Cagrilintide'],
    notes: 'FDA-approved. Contraindicated in personal/family history of medullary thyroid cancer or MEN2. Gastrointestinal side effects (nausea, constipation) are the dominant reason for discontinuation. Pancreatitis is a known class risk.',
    citations: [
      { title: 'Wilding JPH et al. — STEP 1: Once-Weekly Semaglutide in Adults with Overweight or Obesity. NEJM, 2021.', url: 'https://www.nejm.org/doi/full/10.1056/NEJMoa2032183' },
      { title: 'Overgaard RV et al. — Pharmacokinetics of semaglutide in T2D. Clin Pharmacokinet, 2021.', url: 'https://pubmed.ncbi.nlm.nih.gov/33856655/' },
      { title: 'FDA label — Ozempic / Wegovy / Rybelsus Prescribing Information. US FDA, Current.', url: 'https://www.accessdata.fda.gov/' },
    ],
  },
  {
    id: 'tirz',
    name: 'Tirzepatide',
    subtitle: 'Dual GIP/GLP-1 agonist (Mounjaro®)',
    class: 'METABOLIC / INCRETIN',
    color: '#2A6BB5',
    sequence: '39 aa GIP-backbone with GLP-1 elements + C20 fatty diacid',
    formula: 'C225H348F2N48O68',
    mw: '4,813.45 g/mol',
    halfLife: '~5 days (≈117 h)',
    route: 'SubQ weekly',
    dose: '2.5–15 mg weekly (titrated)',
    defaultDoseMcg: 2500,
  commonVialSizes: [5, 10, 20, 50],
    freq: 'Once weekly',
    reconstitution: 'Pre-filled pens (Mounjaro / Zepbound) are standard. Research powder: 10 mg + 2 mL BAC = 5 mg/mL · 5 units = 250 mcg / 50 units = 2.5 mg starting dose. Titrate weekly per clinical protocol.',
    summary: 'The first dual GIP/GLP-1 receptor co-agonist. Built on a GIP-derived peptide backbone with engineered GLP-1R activity, conjugated to a C20 fatty diacid for albumin binding. Produces greater weight loss than semaglutide in head-to-head trials (SURMOUNT-5).',
    mechanism: 'Dual incretin agonism. Full GIPR agonist; biased, partial GLP-1R agonist with ~20× lower potency at GLP-1R than native GLP-1 — this imbalance is mechanistically distinctive and may underlie the superior efficacy.\n\nInsulin secretion and sensitivity. GIP and GLP-1 both enhance glucose-dependent insulin release; GIP adds insulin-independent metabolic effects in adipose.\n\nAppetite and gastric emptying. Central satiety effects from both receptors; delayed gastric emptying contributes to early satiety and caloric reduction.',
    stacks: ['Semaglutide', 'Retatrutide', 'Cagrilintide'],
    notes: 'FDA-approved for T2D (Mounjaro) and obesity (Zepbound). Same contraindications and side-effect profile as GLP-1 class, plus GIP-specific effects.',
    citations: [
      { title: 'Jastreboff AM et al. — Tirzepatide Once Weekly for the Treatment of Obesity (SURMOUNT-1). NEJM, 2022.', url: 'https://www.nejm.org/doi/full/10.1056/NEJMoa2206038' },
      { title: 'Schneck K et al. — Population pharmacokinetics of tirzepatide. CPT Pharmacometrics Syst Pharmacol, 2024.', url: 'https://ascpt.onlinelibrary.wiley.com/doi/10.1002/psp4.13099' },
    ],
  },
  {
    id: 'reta',
    name: 'Retatrutide',
    subtitle: 'Triple GIP/GLP-1/GCG agonist',
    class: 'METABOLIC / INCRETIN',
    color: '#2A6BB5',
    sequence: 'Chimeric peptide w/ balanced GIPR, GLP-1R, GCGR affinity',
    formula: 'C221H343N45O68',
    mw: '~4,731 g/mol',
    halfLife: '~6 days',
    route: 'SubQ weekly',
    dose: 'Phase III trials: 1–12 mg weekly (titrated)',
    defaultDoseMcg: 1000,
  commonVialSizes: [5, 10, 20, 50],
    freq: 'Once weekly',
    reconstitution: 'Investigational; not commercially available. Research powder: 10 mg + 2 mL BAC = 5 mg/mL · 20 units = 1 mg starting dose. Titrate every 4 weeks; max studied 12 mg/week.',
    summary: 'The first triple agonist targeting GIPR, GLP-1R, and the glucagon receptor (GCGR). Phase II obesity trial (Jastreboff 2023) showed mean weight reduction of 24.2% at 48 weeks with 12 mg weekly. Phase III TRIUMPH program ongoing; not FDA-approved as of April 2026.',
    mechanism: 'GLP-1R + GIPR (as in tirzepatide). Combined incretin effect: insulin secretion, appetite suppression, delayed gastric emptying.\n\nGCGR agonism. Glucagon receptor activation in liver increases energy expenditure via hepatic fat oxidation and thermogenesis — a novel axis for weight loss not addressed by GLP-1 or GIP alone.\n\nBalanced affinity. Designed to avoid dominance of any single receptor — the engineering challenge is preventing GCGR-driven hyperglycemia at efficacious doses.',
    stacks: ['Semaglutide', 'Tirzepatide'],
    notes: 'Phase 3 investigational drug. Triple agonist — titrate SLOWER than semaglutide / tirzepatide. Common research protocol: start 1 mg/week, raise by 1–2 mg every 4 weeks, max studied 12 mg/week. Investigational only as of 2026. Not available through legitimate prescribing channels. Present in compounded \'research chemical\' supply with associated quality/safety risks. App should flag status.',
    citations: [
      { title: 'Jastreboff AM et al. — Triple-Hormone-Receptor Agonist Retatrutide for Obesity. NEJM, 2023.', url: 'https://www.nejm.org/doi/full/10.1056/NEJMoa2301972' },
      { title: 'Samms RJ et al. — GIP/GLP-1/glucagon triple agonists. Front Endocrinol, 2023.', url: 'https://doi.org/10.3389/fendo.2023.1107611' },
    ],
  },
  {
    id: 'lira',
    name: 'Liraglutide',
    subtitle: 'Shorter-acting GLP-1 agonist',
    class: 'METABOLIC / GLP-1',
    color: '#2A6BB5',
    sequence: 'GLP-1(7-37) with C16 fatty acid at Lys26',
    formula: 'C172H265N43O51',
    mw: '3,751.20 g/mol',
    halfLife: '~13 h',
    route: 'SubQ daily',
    dose: '0.6–3.0 mg daily (titrated)',
    defaultDoseMcg: 600,
    freq: 'Once daily (titrated weekly)',
    reconstitution: 'Pre-filled pens (Saxenda / Victoza) are standard. Research powder: 5 mg + 2 mL BAC = 2.5 mg/mL · 24 units = 600 mcg starting dose. Titrate weekly toward 3 mg / day.',
    summary: 'The first lipidated GLP-1 analog. Uses a C16 fatty acid linker (shorter than semaglutide\'s C18 diacid), giving once-daily rather than once-weekly dosing. Largely superseded clinically by semaglutide but retains market presence for titration-sensitive patients.',
    mechanism: 'GLP-1R agonism. Full agonist; same pathway as semaglutide.\n\nShorter albumin-binding kinetics. C16 diacid binds albumin less tightly than semaglutide\'s C18 — daily rather than weekly dosing required.',
    stacks: ['Semaglutide', 'Tirzepatide'],
    notes: 'FDA-approved. Same class contraindications as semaglutide.',
    citations: [
      { title: 'Pi-Sunyer X et al. — SCALE: liraglutide for weight management. NEJM, 2015.', url: 'https://pubmed.ncbi.nlm.nih.gov/26132939/' },
    ],
  },
  {
    id: 'cagri',
    name: 'Cagrilintide',
    subtitle: 'Long-acting amylin analog',
    class: 'METABOLIC / AMYLIN',
    color: '#2A6BB5',
    sequence: 'Amylin analog with fatty acid modification',
    formula: 'Long-acting amylin analog (sequence not fully disclosed)',
    mw: '~3,800 g/mol',
    halfLife: '~7 days',
    route: 'SubQ weekly',
    dose: '0.3–2.4 mg weekly (combined with semaglutide as CagriSema)',
    defaultDoseMcg: 300,
    freq: 'Once weekly',
    reconstitution: 'Pre-filled pens in CagriSema combination product. Research powder: 5 mg + 2 mL BAC = 2.5 mg/mL · 12 units = 300 mcg starting dose. Titrate weekly per protocol.',
    summary: 'A long-acting amylin analog being co-developed as CagriSema — a fixed combination with semaglutide. Amylin complements GLP-1 action by slowing gastric emptying and suppressing glucagon independently. Phase III trials show weight loss approaching tirzepatide levels.',
    mechanism: 'Amylin / calcitonin receptor complex agonism. Activates AMY1/2/3 receptors in the area postrema and hypothalamus.\n\nGastric emptying and satiety. Amylin-specific satiety signals synergize with GLP-1\'s hypothalamic effects.',
    stacks: ['Semaglutide'],
    notes: 'Not yet FDA-approved as of April 2026. Investigational.',
    citations: [
      { title: 'Enebo LB et al. — Safety, tolerability, PK of cagrilintide. Lancet, 2021.', url: 'https://pubmed.ncbi.nlm.nih.gov/33894832/' },
    ],
  },
  {
    id: 'aod',
    name: 'AOD-9604',
    subtitle: 'hGH fragment 176-191',
    class: 'METABOLIC / FAT LOSS',
    color: '#2A6BB5',
    sequence: 'hGH(177-191) with N-terminal Tyr',
    formula: 'C78H123N23O23S2',
    mw: '1,815.12 g/mol',
    halfLife: '~30 min – 1 h',
    route: 'SubQ',
    dose: '250–500 mcg daily',
    defaultDoseMcg: 300,
    freq: 'Once daily (5 days on / 2 off in some protocols)',
    reconstitution: '5 mg + 2 mL BAC = 2.5 mg/mL · 10 units = 250 mcg',
    summary: 'A synthetic fragment of the lipolytic C-terminus of human growth hormone. Retains GH\'s fat-mobilizing effects without stimulating IGF-1 or growth. Phase II human trials for obesity were modest (~2–3% weight loss over 12 weeks).',
    mechanism: 'Lipolysis. Acts on β3-adrenergic pathway in adipocytes to stimulate triglyceride hydrolysis and fat oxidation.\n\nNo somatogenic activity. Lacks the growth-promoting domains of hGH — no IGF-1 rise, no tissue proliferation effects.',
    stacks: ['Retatrutide', 'Semaglutide'],
    notes: 'Clinical efficacy is modest; often used as adjunct, not monotherapy.',
    citations: [
      { title: 'Ng FM et al. — Metabolic studies of a synthetic lipolytic domain of hGH. Horm Res, 2000.', url: 'https://pubmed.ncbi.nlm.nih.gov/10965204/' },
    ],
  },
  {
    id: 'amq',
    name: '5-Amino-1MQ',
    subtitle: 'NNMT inhibitor (oral)',
    class: 'METABOLIC / SMALL MOLECULE',
    color: '#2A6BB5',
    sequence: 'Not a peptide — small-molecule NNMT inhibitor',
    formula: 'C10H13N3',
    mw: '175.23 g/mol',
    halfLife: '~5 h',
    route: 'Oral',
    dose: '50–150 mg orally, daily',
    defaultDoseMcg: 50000,
    freq: 'Once daily (oral)',
    reconstitution: 'Typically supplied as capsules, not a vial/reconstitution',
    summary: 'A small-molecule inhibitor of nicotinamide N-methyltransferase (NNMT), included in the peptide catalog because of its frequent pairing with peptide fat-loss protocols. Preclinical work shows NNMT inhibition restores white adipose tissue metabolic flexibility and supports lean mass retention during caloric restriction.',
    mechanism: 'NNMT inhibition. Blocks NNMT-mediated methylation of nicotinamide, preserving the NAD■ salvage pool and methyl donor availability.\n\nAdipocyte metabolic flexibility. Restores insulin sensitivity and fatty acid oxidation in white adipose tissue in high-fat-diet rodent models.',
    stacks: ['Retatrutide', 'Semaglutide', 'MOTS-c'],
    notes: 'Not a peptide — include in catalog with clear classification.',
    citations: [
      { title: 'Kraus D et al. — NNMT regulates energy expenditure in WAT. Nature, 2014.', url: 'https://pubmed.ncbi.nlm.nih.gov/24717514/' },
    ],
  },
  {
    id: 'motsc',
    name: 'MOTS-c',
    subtitle: 'Mitochondrial-derived peptide',
    class: 'METABOLIC / MITOCHONDRIAL',
    color: '#2A6BB5',
    sequence: '16 aa encoded within 12S rRNA region',
    formula: 'C79H120N22O25S2',
    mw: '1,800.10 g/mol',
    halfLife: '~4–6 h (plasma); cellular effects via AMPK persist ~72 h',
    route: 'SubQ (reconstitute in 0.9% NaCl BAC to reduce injection welts)',
    dose: '5–10 mg per dose',
    defaultDoseMcg: 7500,
  commonVialSizes: [5, 10, 25, 50],
    freq: '2–3× weekly',
    reconstitution: '10 mg + 1 mL sterile water or 0.9% saline = 10 mg/mL · 50 units = 5 mg (low-end dose) · 75 units = 7.5 mg · 100 units = 10 mg. BAC water acceptable but may reduce stability past 30 days.',
    summary: 'A 16-amino-acid peptide encoded within the mitochondrial 12S rRNA gene. Released in response to exercise and metabolic stress, MOTS-c is the \'exercise mimetic\' most strongly supported by mitochondrial biology. Activates the AMPK pathway — the same energy-sensor triggered by physical training.',
    mechanism: 'AMPK activation (Folate–AICAR–AMPK axis). Disrupts folate-mediated one-carbon metabolism, elevating AICAR and activating AMPK — the master regulator of cellular energy balance.\n\nNuclear translocation. Under stress, MOTS-c translocates to the nucleus and regulates genes with antioxidant response elements (ARE).\n\nFat oxidation and insulin sensitivity. Increases β-oxidation, reduces hepatic steatosis, and improves insulin sensitivity in diet-induced obese mice.',
    stacks: ['Retatrutide', 'Tirzepatide'],
    notes: 'Reconstitute in saline-based BAC (0.9% NaCl) to reduce localized welts at injection sites. Effects persist ~72 h per dose — 2–3×/wk is standard.',
    citations: [
      { title: 'Lee C et al. — The Mitochondrial-Derived Peptide MOTS-c Promotes Metabolic Homeostasis. Cell Metab, 2015.', url: 'https://doi.org/10.1016/j.cmet.2015.02.009' },
      { title: 'Wan W et al. — MOTS-c in stress, metabolism, and aging. J Transl Med, 2023.', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9854231/' },
    ],
  },
  {
    id: 'selank',
    name: 'Selank',
    subtitle: 'Anxiolytic heptapeptide',
    class: 'COGNITIVE / ANXIOLYTIC',
    color: '#B85FAE',
    sequence: 'Thr-Lys-Pro-Arg-Pro-Gly-Pro (synthetic analog of tuftsin)',
    formula: 'C33H57N11O9',
    mw: '751.87 g/mol',
    halfLife: '~30 min (intranasal), <10 min (IV)',
    route: 'Intranasal (primary) · SubQ (occasional)',
    dose: '250–500 mcg intranasal, 2–3× daily',
    defaultDoseMcg: 300,
    freq: '2–3× daily',
    reconstitution: '5 mg + 5 mL BAC = 1 mg/mL · 0.25 mL = 250 mcg',
    summary: 'A synthetic analog of the immunomodulatory peptide tuftsin, developed in Russia in the 1990s. Approved in Russia for anxiety disorders. Blood-brain-barrier penetrant via intranasal route. N-acetylated variant (\'N-Acetyl Selank\') has extended half-life.',
    mechanism: 'GABAergic modulation. Enhances GABA-A receptor function indirectly, producing anxiolytic effects without sedation or tolerance — a clinically distinctive profile.\n\nBDNF elevation. Increases BDNF mRNA expression in the hippocampus in rodent models, suggesting plasticity-supporting effects.\n\nEnkephalin upregulation. Boosts endogenous enkephalin expression, contributing to mood-stabilizing effects.',
    stacks: ['Semax'],
    notes: 'Not FDA-approved; approved in Russia. Intranasal spray is standard. Research use only in the US. ',
    citations: [
      { title: 'Kozlovskii II et al. — Selank efficacy in anxiety disorders. Russian Journal of Psychiatry, 2001. Russian-language reference', url: '' },
    ],
  },
  {
    id: 'semax',
    name: 'Semax',
    subtitle: 'Nootropic ACTH(4-10) analog',
    class: 'COGNITIVE / NOOTROPIC',
    color: '#B85FAE',
    sequence: 'Met-Glu-His-Phe-Pro-Gly-Pro (ACTH(4-7) analog)',
    formula: 'C37H51N9O10S',
    mw: '813.94 g/mol',
    halfLife: '~1–3 min (acetylated variant: 30+ min)',
    route: 'Intranasal (primary)',
    dose: '200–600 mcg intranasal, 1–3× daily',
    defaultDoseMcg: 400,
    freq: '1–3× daily; morning emphasis',
    reconstitution: '5 mg + 5 mL BAC = 1 mg/mL · 0.2 mL = 200 mcg',
    summary: 'A synthetic analog of ACTH fragment 4-10 developed in Russia. Retains neurotrophic / nootropic effects without HPA-axis activation. Used clinically in Russia for stroke recovery and cognitive enhancement. N-acetylated variant has meaningfully extended half-life.',
    mechanism: 'BDNF / NGF upregulation. Elevates brain-derived neurotrophic factor and nerve growth factor in limbic and cortical regions.\n\nDopaminergic modulation. Enhances dopaminergic transmission in the nucleus accumbens — proposed mechanism for attention and motivation effects.\n\nNeuroprotection. Reduces infarct size in rodent stroke models; approved in Russia as adjunct in ischemic stroke recovery.',
    stacks: ['Selank'],
    notes: 'Not FDA-approved; approved in Russia. Intranasal only.',
    citations: [
      { title: 'Dolotov OV et al. — Semax, an analog of ACTH(4-10), regulates BDNF. J Neurochem, 2006.', url: 'https://pubmed.ncbi.nlm.nih.gov/16684336/' },
    ],
  },
  {
    id: 'cerebro',
    name: 'Cerebrolysin',
    subtitle: 'Porcine-derived brain peptide mixture',
    class: 'COGNITIVE / NEUROTROPHIC',
    color: '#B85FAE',
    sequence: 'Enzymatic hydrolysate of porcine brain tissue',
    formula: 'Heterogeneous',
    mw: 'Mixture; components <10 kDa',
    halfLife: 'Varies by component',
    route: 'IM · IV infusion',
    dose: '5–30 mL IM (clinical protocols) per session',
    defaultDoseMcg: 5000,
    freq: 'Daily for 10–20 days in cycles',
    reconstitution: 'Pre-formulated ampoules; no reconstitution required',
    summary: 'A peptidergic preparation derived from enzymatic hydrolysis of porcine brain tissue. Used clinically in Europe, Asia, and Russia for stroke, dementia, and TBI. Contains peptide fragments <10 kDa with neurotrophic factor-like activity.',
    mechanism: 'Neurotrophic mimicry. Components mimic BDNF, GDNF, CNTF, and NGF activity in cultured neurons.\n\nAnti-apoptotic. Reduces caspase-3 activation in ischemic and excitotoxic models.\n\nSynaptogenesis. Enhances dendritic arborization and synapse formation.',
    stacks: ['Dihexa'],
    notes: 'Not FDA-approved. Approved in 40+ countries including Russia, China, Austria. Administered in clinical courses, not continuous use.',
    citations: [
      { title: 'Muresanu DF et al. — Cerebrolysin in stroke and TBI. CNS Neurol Disord Drug Targets, 2014.', url: 'https://pubmed.ncbi.nlm.nih.gov/25230225/' },
    ],
  },
  {
    id: 'dihexa',
    name: 'Dihexa',
    subtitle: 'Angiotensin IV analog (oral-active)',
    class: 'COGNITIVE / NOOTROPIC',
    color: '#B85FAE',
    sequence: 'N-hexanoic-Tyr-Ile-(6) aminohexanoic amide',
    formula: 'C34H54N6O5',
    mw: '626.83 g/mol',
    halfLife: '~10 h (oral)',
    route: 'Oral · Transdermal',
    dose: 'Not yet established in humans; rodent studies use 0.25–2 mg/kg oral',
    defaultDoseMcg: 250,
    freq: 'Variable; daily in research',
    reconstitution: 'Often supplied in oil-based carrier, not aqueous vial',
    summary: 'A small-molecule angiotensin IV analog. Preclinical work (Washington State / Harding lab) reports dendritic spine formation and cognitive rescue in rodent Alzheimer\'s models. No human clinical trials. Often grouped with peptides despite being a peptidomimetic.',
    mechanism: 'HGF/c-Met activation. Potentiates hepatocyte growth factor signaling through the c-Met receptor — a novel synaptogenic pathway.\n\nDendritic spine formation. Induces rapid formation of functional synapses in hippocampal slice cultures at picomolar concentrations.',
    stacks: [],
    notes: 'Human safety and efficacy unknown. Experimental only.',
    citations: [
      { title: 'Benoist CC et al. — The angiotensin IV analog dihexa facilitates learning. J Pharmacol Exp Ther, 2014.', url: 'https://pubmed.ncbi.nlm.nih.gov/24958612/' },
    ],
  },
  {
    id: 'epi',
    name: 'Epitalon',
    subtitle: 'Pineal tetrapeptide (Ala-Glu-Asp-Gly)',
    class: 'LONGEVITY / BIOREGULATOR',
    color: '#4AAE9B',
    sequence: 'Ala-Glu-Asp-Gly (tetrapeptide)',
    formula: 'C14H22N4O9',
    mw: '390.35 g/mol',
    halfLife: '~30 min (plasma)',
    route: 'SubQ · Intranasal',
    dose: '5–10 mg/day for 10–20 days per cycle',
    defaultDoseMcg: 5000,
  commonVialSizes: [10, 20, 50, 100],
    freq: 'Daily for 10–20 days, 2–4× per year',
    reconstitution: '10 mg + 1 mL BAC = 10 mg/mL · 50 units = 5 mg (typical Khavinson protocol dose)',
    summary: 'A tetrapeptide developed by Vladimir Khavinson at the St. Petersburg Institute of Bioregulation and Gerontology. Long-running Russian studies report telomerase activation and lifespan-extending effects in rodents. Human clinical evidence is primarily from Russian studies with varied methodology.',
    mechanism: 'Telomerase activation. Epitalon has been shown to upregulate telomerase activity in human somatic cells in vitro, with corresponding telomere-length extension.\n\nCircadian regulation. Restores pineal melatonin rhythm in aged animals.\n\nAnti-cancer effects (rodents). Reduced spontaneous tumor incidence in several rodent strains.',
    stacks: [],
    notes: 'Cycled dosing (10–20 days on, then off) is the classical protocol.',
    citations: [
      { title: 'Khavinson VK et al. — Peptide epitalon activates chromatin. Bull Exp Biol Med, 2003.', url: 'https://pubmed.ncbi.nlm.nih.gov/14737220/' },
      { title: 'Anisimov VN et al. — Effect of epitalon on biomarkers of aging. Biogerontology, 2003.', url: 'https://pubmed.ncbi.nlm.nih.gov/12815195/' },
    ],
  },
  {
    id: 'ss31',
    name: 'SS-31 (Elamipretide)',
    subtitle: 'Mitochondria-targeted tetrapeptide',
    class: 'LONGEVITY / MITOCHONDRIAL',
    color: '#4AAE9B',
    sequence: 'D-Arg-dimethylTyr-Lys-Phe-NH■',
    formula: 'C32H49N9O5',
    mw: '639.80 g/mol',
    halfLife: '~2.5–5 h (SubQ)',
    route: 'SubQ',
    dose: '5–40 mg SubQ daily (clinical trial range)',
    defaultDoseMcg: 5000,
  commonVialSizes: [5, 10, 25, 50],
    freq: 'Once daily',
    reconstitution: '10 mg + 2 mL BAC = 5 mg/mL · 100 units (1 mL) = 5 mg (low-end clinical dose)',
    summary: 'An aromatic-cationic tetrapeptide that selectively partitions into the inner mitochondrial membrane, binding cardiolipin and stabilizing electron transport chain function. Phase III trials for Barth syndrome and primary mitochondrial myopathy conducted; not FDA-approved as of 2026.',
    mechanism: 'Cardiolipin binding. Preferentially accumulates in the inner mitochondrial membrane, stabilizing cardiolipin-dependent respiratory-chain supercomplexes.\n\nROS reduction. Reduces mitochondrial reactive oxygen species generation without affecting physiologic ROS signaling.\n\nCristae remodeling. Preserves cristae morphology under stress, maintaining ATP synthesis efficiency.',
    stacks: ['MOTS-c'],
    notes: 'Investigational; Stealth BioTherapeutics has run multiple clinical programs.',
    citations: [
      { title: 'Szeto HH — Cell-permeable, mitochondrial-targeted, peptide antioxidants. AAPS J, 2006.', url: '' },
    ],
  },
  {
    id: 'nad',
    name: 'NAD+',
    subtitle: 'Injectable nicotinamide adenine dinucleotide',
    class: 'LONGEVITY / COENZYME',
    color: '#4AAE9B',
    sequence: 'Not a peptide — coenzyme',
    formula: 'C21H27N7O14P2',
    mw: '663.43 g/mol',
    halfLife: 'Short in plasma; tissue uptake sustains effect',
    route: 'SubQ · IM · IV (clinical)',
    dose: '100–500 mg SubQ per session (clinic IV: 250–1,000 mg)',
    defaultDoseMcg: 100000,
  commonVialSizes: [100, 250, 500, 1000],
    freq: 'Weekly to daily SubQ; IV cycles 5–10 days',
    reconstitution: '500 mg + 5 mL BAC = 100 mg/mL · 100 units (1 mL) = 100 mg. Push slowly — flushing/nausea is rate-dependent.',
    summary: 'Not a peptide, but included in most peptide catalogs because it\'s administered injectably alongside peptides. NAD■ is the central redox coenzyme and substrate for sirtuins and PARPs. Supplementation aims to offset the age-related decline in tissue NAD■ levels.',
    mechanism: 'Sirtuin substrate supply. SIRT1-7 are NAD■-consuming deacetylases; NAD■ availability is rate-limiting for sirtuin activity.\n\nRedox balance. NAD■/NADH ratio regulates cellular metabolic state — low ratios associated with metabolic dysfunction.\n\nPARP / DNA repair. PARPs consume NAD■ during DNA damage response.',
    stacks: ['MOTS-c', 'SS-31 (Elamipretide)'],
    notes: 'SubQ injections can cause intense flushing / chest tightness during administration — slow infusion and smaller doses mitigate this.',
    citations: [
      { title: 'Rajman L et al. — Therapeutic potential of NAD-boosting molecules. Cell Metab, 2018.', url: 'https://pubmed.ncbi.nlm.nih.gov/29514064/' },
    ],
  },
  {
    id: 'foxo',
    name: 'FOXO4-DRI',
    subtitle: 'Senolytic peptide',
    class: 'LONGEVITY / SENOLYTIC',
    color: '#4AAE9B',
    sequence: 'Retro-inverso D-amino acid FOXO4 fragment',
    formula: 'D-Retro-Inverso peptide of FOXO4 (sequence proprietary)',
    mw: '~4,500 g/mol',
    halfLife: 'Limited PK data',
    route: 'SubQ · IV (rodent)',
    dose: 'Not established in humans; rodent studies use 5 mg/kg 3× over 10 days',
    defaultDoseMcg: 5000,
    freq: 'Cycled dosing (rodent protocol: 3 doses over 10 days)',
    reconstitution: 'Not standardized',
    summary: 'An experimental senolytic peptide designed by Peter de Keizer\'s lab (Erasmus MC) to disrupt the FOXO4-p53 interaction, triggering apoptosis selectively in senescent cells. Mouse studies show hair regrowth, renal function restoration, and physical activity gains. No human trials; independent replication is limited.',
    mechanism: 'FOXO4-p53 disruption. In senescent cells, FOXO4 sequesters p53 in the nucleus, preventing apoptosis. FOXO4-DRI competitively displaces FOXO4, releasing p53 to trigger selective senolysis.',
    stacks: [],
    notes: 'Experimental only. Not available through legitimate prescribing; research chemical supply chains have quality concerns. App should flag investigational status prominently.',
    citations: [
      { title: 'Baar MP et al. — Targeted apoptosis of senescent cells restores tissue homeostasis. Cell, 2017.', url: 'https://pubmed.ncbi.nlm.nih.gov/28340339/' },
    ],
  },
  {
    id: 'humanin',
    name: 'Humanin',
    subtitle: 'Mitochondrial-derived cytoprotective peptide',
    class: 'LONGEVITY / MITOCHONDRIAL',
    color: '#4AAE9B',
    sequence: '24 aa encoded in mitochondrial 16S rRNA',
    formula: 'C123H193N35O33S2',
    mw: '2,687.15 g/mol',
    halfLife: '~30 min (linear); variants (HNG) extend this',
    route: 'SubQ · IV',
    dose: 'Research only; no human consensus protocol',
    defaultDoseMcg: 250,
    freq: 'Varies by study',
    reconstitution: '5 mg + 2 mL BAC = 2.5 mg/mL · 10 units = 250 mcg (no human consensus protocol; ranges vary by study)',
    summary: 'A 24-amino-acid peptide encoded by an open reading frame in mitochondrial 16S rRNA. Identified as a suppressor of Alzheimer\'s-related neuronal death. The modified variant \'HNG\' (Gly→Ser at position 14) has dramatically increased potency. Both remain experimental.',
    mechanism: 'Anti-apoptotic. Binds and inhibits pro-apoptotic Bax translocation to mitochondria; suppresses IAPP- and Aβ-induced cell death.\n\nMetabolic regulation. Improves insulin sensitivity and reduces hepatic glucose output in rodent metabolic models.',
    stacks: [],
    notes: 'Experimental; no established clinical protocols.',
    citations: [
      { title: 'Hashimoto Y et al. — Humanin rescues cells from Alzheimer\'s-related death. Proc Natl Acad Sci USA, 2001.', url: 'https://pubmed.ncbi.nlm.nih.gov/11371652/' },
    ],
  },
  {
    id: 'pt141',
    name: 'PT-141 (Bremelanotide)',
    subtitle: 'Melanocortin agonist (Vyleesi®)',
    class: 'SEXUAL HEALTH / MELANOCORTIN',
    color: '#D94F6B',
    sequence: 'Ac-Nle-Asp-His-D-Phe-Arg-Trp-Lys-OH (cyclic)',
    formula: 'C50H68N14O10',
    mw: '1,025.18 g/mol',
    halfLife: '~2 h',
    route: 'SubQ (lower abdomen or thigh)',
    dose: '0.75–1.75 mg SubQ per dose (FDA-approved label: 1.75 mg)',
    defaultDoseMcg: 1000,
  commonVialSizes: [5, 10, 20],
    freq: 'As-needed; max 1 dose / 24h and 8 doses / month',
    reconstitution: '10 mg + 2 mL BAC = 5 mg/mL · 20 units = 1 mg',
    summary: 'FDA-approved for hypoactive sexual desire disorder (HSDD) in premenopausal women (Vyleesi, 2019). Melanocortin-4 receptor agonist acting centrally in the medial preoptic nucleus. Effective in both sexes in research; off-label use in men for erectile dysfunction is common.',
    mechanism: 'MC4R agonism. Activates melanocortin-4 receptors in the medial preoptic nucleus of the hypothalamus — the central hub of sexual arousal circuitry.\n\nDopaminergic downstream. MC4R activation increases dopamine release in the nucleus accumbens, contributing to sexual motivation effects.',
    stacks: ['Melanotan II'],
    notes: 'Common side effects: nausea (most common), flushing, transient blood pressure elevation. Contraindicated in uncontrolled hypertension.',
    citations: [
      { title: 'Kingsberg SA et al. — Bremelanotide for Hypoactive Sexual Desire Disorder. Obstet Gynecol, 2019.', url: '' },
    ],
  },
  {
    id: 'mt2',
    name: 'Melanotan II',
    subtitle: 'Non-selective melanocortin agonist',
    class: 'SEXUAL HEALTH / MELANOCORTIN',
    color: '#D94F6B',
    sequence: 'Ac-Nle-cyclo[Asp-His-D-Phe-Arg-Trp-Lys]-NH■',
    formula: 'C50H69N15O9',
    mw: '1,024.18 g/mol',
    halfLife: '~33 h (long-acting)',
    route: 'SubQ',
    dose: '0.25–1 mg SubQ (titrate slowly from 0.25 mg)',
    defaultDoseMcg: 250,
  commonVialSizes: [10, 20, 30],
    freq: 'Daily during loading (7–14 days), then as-needed',
    reconstitution: '10 mg + 2 mL BAC = 5 mg/mL · 2 units = 100 mcg',
    summary: 'A cyclic heptapeptide non-selective melanocortin agonist originally investigated as a pharmacologic tanning agent. Activates MC1R (melanin), MC3R, MC4R (sexual arousal), and MC5R. Side-effect profile (nausea, flushing, darkening of moles) is substantial. Not FDA-approved.',
    mechanism: 'Multi-MCR agonism. Non-selective agonist at MC1R (pigmentation), MC3R, MC4R (libido), and MC5R — effects overlap with PT-141 plus pigmentation.',
    stacks: ['PT-141 (Bremelanotide)'],
    notes: 'Darkening of existing moles is reported; annual dermatology follow-up recommended during use.',
    citations: [
    ],
  },
  {
    id: 'kiss10',
    name: 'Kisspeptin-10',
    subtitle: 'GnRH-stimulating decapeptide',
    class: 'HORMONAL / HPG AXIS',
    color: '#E08A5F',
    sequence: 'Tyr-Asn-Trp-Asn-Ser-Phe-Gly-Leu-Arg-Phe-NH■',
    formula: 'C63H83N17O14',
    mw: '1,302.48 g/mol',
    halfLife: '~4 min (rapid)',
    route: 'SubQ · IV',
    dose: '1 nmol/kg IV bolus (clinical research); 200 mcg SubQ (ad-hoc)',
    defaultDoseMcg: 200,
  commonVialSizes: [1, 2, 5, 10],
    freq: 'Single doses in diagnostic protocols',
    reconstitution: '1 mg + 1 mL BAC = 1 mg/mL · 10 units = 100 mcg',
    summary: 'The physiologic trigger of gonadotropin-releasing hormone (GnRH) release from the hypothalamus. Used investigationally as a diagnostic agent for hypogonadotropic hypogonadism and in fertility induction. Administered for its \'testosterone boost\' effect off-label.',
    mechanism: 'KISS1R agonism. Activates GPR54 (KISS1R) on hypothalamic GnRH neurons, triggering GnRH release, LH/FSH pulses, and downstream testosterone or estradiol production.',
    stacks: [],
    notes: 'Ultra-short half-life limits utility. Best characterized as a diagnostic or acute reproductive research tool.',
    citations: [
      { title: 'Dhillo WS et al. — Kisspeptin-54 stimulates gonadotropin release in men. J Clin Endocrinol Metab, 2005.', url: 'https://pubmed.ncbi.nlm.nih.gov/16174720/' },
    ],
  },
  {
    id: 'oxy',
    name: 'Oxytocin',
    subtitle: 'Social-bonding nonapeptide',
    class: 'NEUROPEPTIDE',
    color: '#8B6FBF',
    sequence: 'Cys-Tyr-Ile-Gln-Asn-Cys-Pro-Leu-Gly-NH■ (disulfide)',
    formula: 'C43H66N12O12S2',
    mw: '1,007.19 g/mol',
    halfLife: '~1–6 min (IV); longer intranasal tissue effect',
    route: 'Intranasal · IV (obstetric) · SubQ (rare)',
    dose: '10–40 IU intranasal (research); obstetric IV dosing differs',
    defaultDoseMcg: 16,
    freq: 'As needed (intranasal research)',
    reconstitution: 'Pre-formulated nasal sprays standard',
    summary: 'A nine-amino-acid cyclic neuropeptide. Medical use is for labor induction and postpartum hemorrhage (IV Pitocin®). Intranasal formulations are used off-label / in research for social cognition, autism spectrum studies, and post-traumatic conditions. Short half-life and blood-brain-barrier limitations constrain utility.',
    mechanism: 'OXTR agonism. Activates the oxytocin receptor in smooth muscle (uterus, breast) and central nervous system (amygdala, hypothalamus, brainstem).',
    stacks: [],
    notes: 'FDA-approved as Pitocin for obstetric use; intranasal off-label.',
    citations: [
      { title: 'Leng G, Sabatier N — Oxytocin — the sweet hormone. Trends Endocrinol Metab, 2017.', url: 'https://pubmed.ncbi.nlm.nih.gov/28655491/' },
    ],
  },
  {
    id: 'dsip',
    name: 'DSIP',
    subtitle: 'Delta Sleep-Inducing Peptide',
    class: 'SLEEP / NEUROPEPTIDE',
    color: '#5B7FC9',
    sequence: 'Trp-Ala-Gly-Gly-Asp-Ala-Ser-Gly-Glu (nonapeptide)',
    formula: 'C35H48N10O15',
    mw: '848.81 g/mol',
    halfLife: '~7 min (plasma)',
    route: 'SubQ · Intranasal',
    dose: '100–500 mcg SubQ 30–60 min before bed',
    defaultDoseMcg: 250,
    freq: 'Nightly as needed',
    reconstitution: '5 mg + 2 mL BAC = 2.5 mg/mL · 4 units = 100 mcg',
    summary: 'A 9-amino-acid peptide isolated in the 1970s from rabbit brain during electrically-induced sleep. Human clinical literature is older and inconsistent — some sleep-promoting effects reported, others null. Sometimes used as adjunct in withdrawal protocols.',
    mechanism: 'Unknown receptor. Despite 40+ years of study, no specific DSIP receptor has been conclusively identified. Effects may be mediated by multiple CNS neuromodulatory systems.',
    stacks: [],
    notes: 'Short half-life suggests rapid metabolism; clinical effects may depend on downstream signaling rather than peptide presence.',
    citations: [
      { title: 'Graf MV, Schoenenberger GA — Delta sleep-inducing peptide. Neurosci Biobehav Rev, 1986.', url: 'https://pubmed.ncbi.nlm.nih.gov/3554043/' },
    ],
  },
  {
    id: 'igflr3',
    name: 'IGF-1 LR3',
    subtitle: 'Long-R3 IGF-1',
    class: 'ANABOLIC / GROWTH FACTOR',
    color: '#8B5A3C',
    sequence: '83 aa; IGF-1 with Arg3 sub + 13-aa N-terminal extension',
    formula: 'C400H625N111O115S9',
    mw: '9,111 g/mol',
    halfLife: '~20–30 h (LR3 extends native IGF-1\'s <15 min)',
    route: 'SubQ (site of desired action or general SubQ)',
    dose: '20–50 mcg/day (research); some protocols 50–80 mcg',
    defaultDoseMcg: 30,
  commonVialSizes: [1, 2, 5, 10],
    freq: 'Once daily',
    reconstitution: 'IGF-1 LR3 must be reconstituted with 0.6% acetic acid (NOT BAC water — destroys the peptide). 1 mg + 1 mL acetic acid = 1 mg/mL · 2 units = 20 mcg. Refrigerate after reconstitution; use within 30 days.',
    summary: 'A modified IGF-1 analog with an arginine substitution at position 3 and a 13-amino-acid N-terminal extension. These modifications reduce IGF-binding-protein affinity and extend plasma half-life from <15 minutes to ~24 hours. Used for anabolic effects; hypoglycemia risk is real.',
    mechanism: 'IGF-1 receptor agonism. Activates IGF-1R on muscle, connective tissue, and other targets; drives protein synthesis via PI3K-Akt-mTOR.\n\nReduced IGFBP binding. LR3 modifications lower binding to IGF-binding proteins, increasing free/active peptide in circulation.',
    stacks: ['CJC-1295 (no DAC / Mod GRF 1-29)', 'Ipamorelin'],
    notes: 'Hypoglycemia risk during first exposures — similar caution to insulin. Eat within 20 minutes of dosing during titration.',
    citations: [
      { title: 'Tomas FM et al. — Anabolic effects of IGF-1 LR3 in catabolic states. J Endocrinol, 1993.', url: '' },
    ],
  },
  {
    id: 'igfdes',
    name: 'IGF-1 DES',
    subtitle: 'Des(1-3) IGF-1 truncated',
    class: 'ANABOLIC / GROWTH FACTOR',
    color: '#8B5A3C',
    sequence: 'IGF-1 missing first 3 N-terminal amino acids',
    formula: 'C331H510N90O99S7',
    mw: '~7,400 g/mol',
    halfLife: 'Short (minutes in plasma); strong local action',
    route: 'Intramuscular (local / site injection)',
    dose: '20–75 mcg localized (near target muscle)',
    defaultDoseMcg: 40,
  commonVialSizes: [1, 2, 5, 10],
    freq: 'Daily or per-training-session',
    reconstitution: '1 mg + 1 mL BAC = 1 mg/mL · 5 units = 50 mcg. BAC water is acceptable; some research protocols prefer 0.6% acetic acid for extended (>30d) storage stability.',
    summary: 'An IGF-1 variant lacking the first three N-terminal amino acids, giving ~10× higher potency than native IGF-1 in vitro due to much weaker IGFBP binding. Short plasma half-life favors local/intramuscular injection for site-specific action.',
    mechanism: 'IGF-1R super-agonism. DES truncation reduces IGFBP binding drastically; more free peptide available to activate IGF-1R.\n\nHyperplasia signaling. Preclinical work suggests DES can stimulate satellite-cell proliferation more than native IGF-1, potentially supporting muscle-fiber hyperplasia.',
    stacks: ['IGF-1 LR3', 'CJC-1295 (no DAC / Mod GRF 1-29)'],
    notes: 'Injected locally; hypoglycemia risk lower than LR3 due to rapid clearance.',
    citations: [
    ],
  },
  {
    id: 'pegmgf',
    name: 'PEG-MGF',
    subtitle: 'Pegylated Mechano Growth Factor',
    class: 'ANABOLIC / GROWTH FACTOR',
    color: '#8B5A3C',
    sequence: 'C-terminal E-peptide of IGF-1Ec splice variant',
    formula: 'Variant of IGF-1Ec splice form, PEGylated',
    mw: 'Varies with PEG size',
    halfLife: 'Extended to days via PEGylation',
    route: 'SubQ (local or general)',
    dose: '100–400 mcg per dose',
    defaultDoseMcg: 200,
  commonVialSizes: [2, 5, 10],
    freq: '2–3× weekly',
    reconstitution: '2 mg + 2 mL BAC = 1 mg/mL · 20 units = 200 mcg',
    summary: 'PEGylated form of mechano growth factor, the splice variant of IGF-1 released by muscle in response to mechanical loading. PEGylation extends half-life dramatically. Theoretical role in satellite-cell activation and muscle repair; human clinical data is limited.',
    mechanism: 'Satellite cell activation. MGF\'s C-terminal E-peptide is distinct from mature IGF-1; it preferentially activates quiescent satellite cells in damaged muscle.',
    stacks: ['IGF-1 LR3'],
    notes: 'Primarily used in post-injury/loading research contexts.',
    citations: [
      { title: 'Goldspink G — Mechano growth factor (MGF) and muscle adaptation. J Anat, 2005.', url: 'https://pubmed.ncbi.nlm.nih.gov/15817105/' },
    ],
  },
  {
    id: 'tesofensine',
    name: 'Tesofensine',
    subtitle: 'Oral triple monoamine reuptake inhibitor',
    class: 'METABOLIC / SMALL MOLECULE',
    color: '#2A6BB5',
    sequence: '',
    formula: 'C17H24Cl2N',
    mw: '329.3 g/mol',
    halfLife: '~9 days',
    route: 'Oral (capsule)',
    dose: '250 mcg – 1 mg PO daily',
    defaultDoseMcg: 500,
    freq: 'Daily (morning)',
    reconstitution: 'Oral capsule; no reconstitution needed',
    summary:
      'A triple monoamine-reuptake inhibitor (norepinephrine, dopamine, serotonin) originally developed for Parkinson disease, then repositioned for obesity after phase-2 trials (TIPO-1, TIPO-4) reported significant weight loss. Approved in some jurisdictions for obesity; still investigational in others.',
    mechanism:
      'Inhibits presynaptic reuptake of norepinephrine, dopamine, and serotonin.\n\nReduces appetite and increases satiety signaling in hypothalamic feeding circuits.\n\nModest thermogenic contribution via sympathetic activation.',
    stacks: [],
    notes:
      'Blood-pressure monitoring recommended in trial protocols. Not a peptide (small molecule) but commonly grouped with metabolic peptides in research settings.',
    citations: [
      { title: 'Astrup A et al. — Tesofensine TIPO-1 obesity trial. Lancet, 2008.', url: 'https://pubmed.ncbi.nlm.nih.gov/18950853/' },
    ],
  },
];

export const PEPTIDE_CLASSES = [
  'All',
  'HEALING',
  'IMMUNE',
  'GROWTH',
  'METABOLIC',
  'COGNITIVE',
  'LONGEVITY',
  'SEXUAL HEALTH',
  'HORMONAL',
  'ANABOLIC',
  'SLEEP',
  'NEUROPEPTIDE',
] as const;

export function peptideClassTopLevel(cls: string): string {
  return cls.split('/')[0].trim();
}

export function findPeptide(id: string): Peptide | undefined {
  return PEPTIDES.find((p) => p.id === id);
}
